config/routes.rb
Celtia::Application.routes.draw do


  get "password_resets/new"

  resources :players
  resources :sessions
  resources :password_resets
  resources :game_rooms
  resources :messages do
  
  member do
  
  get "message_list" 
  end
  
  
  end

  resources :games do
   
  #get 'update_game_red', :on => :member, :as => update_game_red

    member do
      get "last_moved"
      get "turn_counter"
      put 'update_game_red'
      post "command"
      post "enginemove2"
      post "enginemovepromote"
      post "enginemovewildcard"
      post "enginemoveresurrect"
      post "enginemoveshapeshift"
      post "enginemovepossession"
      post "enginemoveflight"
      post "enginemovefreeze"
      post "enginemovezap"
      post "enginemoveshield"
      post "enginemovemist"
      post "random_move"
      post "use_ai"
      put "play_as_white"
      put "play_as_red"
      put "play_as_green"
      put "play_as_black"
    end

    #resource :whites, only: [:show]
    #resource :blacks, only: [:show]
    #resource :greens, only: [:show]
    #resource :reds, only: [:show]
  end

  get "/usage", :to => "games#usage", :as => :usage
  get "/story", :to => "home#storyboard", :as => "story"
  get "/lobby", :to => "lobby#show", :as => "playerintro"

  resource :error, only: [:show]

  root to: "games#landing"
end

app/models/game.rb
class Game < ActiveRecord::Base
has_many :player_lists
has_many :messages
#has_many :players, :through => :player_lists
has_many :players, :through => :player_playing_games


  attr_accessible :black, :forfeit, :game_state, :green, :last_moved, :red, :white, :turn_counter, :game_wrapper_id, :num_players
  attr_accessor :engine, :eng_game
  after_create :create_engine

  has_one :game_wrapper
  belongs_to :game_room

  def create_engine
    @engine = Engine::CeltiaRulesEngine.new(false, false, false)
    @engine.handle_line("new #{id} #{num_players == 3 ? 4 : num_players}")
    ObjectCache.add(id.to_s, @engine)
  end
  
  #Probably there exists a better way of doing this. - Sherer
  def update_turn_counter
    case @turn_counter 
    when "player0"
      update_attributes(:turn_counter => "player1")
    when "player1"
      update_attributes(:turn_counter => "player2")
    when "player2"
      update_attributes(:turn_counter => "player3")
    when self.turn_counter == "player3"
      update_attributes(:turn_counter => "player0") 	
    end
  end
  
  # Graham: I think what you had didn't work at all, putting this in for now instead
   #@turn_count = (@turn_count + 1) % 4
   #update_attributes(:turn_counter => "player#{@turn_count}")
    
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_filter :authorize, only: [:create, :show]
  before_filter :update_last_seen, only: [:show, :create, :update, :enginemove2]
  protect_from_forgery :except => [:update, :enginemove2] #MAJOR, MAJOR, REPEAT MAJOR security flaw here. A more robust AJAX solution is needed.
  


  def landing
    @player = Player.new
    render :layout => 'landing'
  end

  def show

    @game_id = params[:game_id] if params[:game_id]
    @game_id = params[:id] if params[:id]
    @game = Game.find_by_id(@game_id)
    @messages = Message.where("game_id = ?", params[:id]).order( 'created_at ASC' )
    @player_playing_game = PlayerPlayingGame.all
    eng = ObjectCache.find(@game_id)
    @eng_game = eng.games[eng.current_game]
    gon.game_state = @game.game_state
    gon.watch.turn_counter = @game.turn_counter
    if !params[:_method].present?

    respond_to do |format|
       format.html
       format.json
       end
    end
    # ----------------when the page is refreshed, detect which player has which spells and enable them----------------
    engine = ObjectCache.find(@game.id.to_s)
    engine.games[engine.current_game].players.each do |i|
      spells = [:flight, :mist, :possess, :freeze, :bolt, :cauldron, :hammer, :shield, :shapeshift]
      spells.each do |s|
        if i.spells[s] == 1
          PrivatePub.publish_to("/games/#{@game.id}", "$('##{s}_button_#{i.turn_order}').removeAttr('disabled');")
        else
          PrivatePub.publish_to("/games/#{@game.id}", "$('##{s}_button_#{i.turn_order}').attr('disabled','disabled');")
        end
      end
    end
    # To show whose turn is it
    PrivatePub.publish_to("/games/#{@game.id}", "$('#chess_board').removeClass('highlighted');")
    @player_to_make_move = engine.games[engine.current_game].players[engine.games[engine.current_game].side_to_move].to_s
    PrivatePub.publish_to("/messages/#{@player_to_make_move}", "$('#chess_board').addClass('highlighted');")
  end

  def index
    if params[:owner]
      @games = Game.where("num_players = ? AND owner = ?", 4, params[:owner]).reject{|g| ObjectCache.find(g.id.to_s).nil?}
      @games2 = Game.where("num_players = ? AND owner = ?", 2, params[:owner]).reject{|g| ObjectCache.find(g.id.to_s).nil?}
      @games3 = Game.where("num_players = ? AND owner = ?", 3, params[:owner]).reject{|g| ObjectCache.find(g.id.to_s).nil?}
      @owner = Player.find_by username: params[:owner]
    else
      @games = Game.where("num_players = 4").reject{|g| ObjectCache.find(g.id.to_s).nil?}
      @games2 = Game.where("num_players = 2").reject{|g| ObjectCache.find(g.id.to_s).nil?}
      @games3 = Game.where("num_players = 3").reject{|g| ObjectCache.find(g.id.to_s).nil?}
    end
  end

  def create
    @game = Game.new({:num_players => params[:num_players].to_i})
    @game.owner = params[:owner]
    @game.save!
    e = ObjectCache.find(@game.id.to_s)
    eng_game = e.games[e.current_game]
    case @game.num_players
    when 3
      eng_game.players[3].piece_list.each do |p|
        p.mercenary= true
      end
      eng_game.players[3].mercenary= true
      eng_game.players[3].active= false
      eng_game.get_moves(eng_game.players[0])
    else
    
    end
    0.upto(3) do |i|
      PlayerPlayingGame.create(:game_id => @game.id, :player_side => "player#{i}")
    end
    @game.update_attributes(:turn_counter => "player0")
    redirect_to game_path(@game)
  end
  
  def update
    @game = Game.find(params[:id])
    
    if @game.black && @game.red && @game.white && @game.green
      @game.update_turn_counter
      @game.update_attributes(game_state: params[:data])
      @game.update_attributes(params[:game])
      
      render nothing: true
    else
      @game.update_attributes(params[:game])
      @game.update_attributes(game_state: params[:data])
      
      update_game_side
      @game.update_turn_counter
      
      redirect_to game_path(@game)
    end    
  end
  
  def enginemove2
    @game = Game.find_by_id(params[:id])
    engine = ObjectCache.find(@game.id.to_s)
    engine.handle_line("move #{params[:fromx]} #{params[:fromy]} #{params[:tox]} #{params[:toy]} #{current_player.username}")
    render text: engine.games[engine.current_game].last_move_okay
    # ------------if last move was ok, publish a refresh trigger to every player in the same room so that every move is reflect in real time-----------
    if engine.games[engine.current_game].last_move_okay == true
      PrivatePub.publish_to("/games/#{@game.id}", 
        "$.ajax({type: 'GET',url: '/games/' + #{@game.id} + '.json',failure: function(msg) {alert('Request unsuccessful, check your internet connection.')},dataType: 'json',success: update});
        $('#chat').append('<li class=\"announcement\"><span class=\"sender\">#{current_player.username}</span> made a move!<span class=\"pull-right small text-muted\">#{DateTime.now.strftime("%H:%M")}</span></li>');
        $('#chess_board').removeClass('highlighted');
        ")
      # To highlight player's board if its his turn
      @player_to_make_move = engine.games[engine.current_game].players[engine.games[engine.current_game].side_to_move].to_s
      PrivatePub.publish_to("/messages/#{@player_to_make_move}", "$('#chess_board').addClass('highlighted');")
      # ----------if a spell is collected, enable the spell button in corresponding player's spell rack------------        
      if engine.games[engine.current_game].spell_list
        # array for all spells
        spells = [:flight, :mist, :possess, :freeze, :bolt, :cauldron, :hammer, :shield, :shapeshift]
        # for each spell, if its value is 1 in spell_list array, meaning it is collected by player, enable the according button
        spells.each do |s|
          if engine.games[engine.current_game].spell_list[s] == 1
            PrivatePub.publish_to("/games/#{@game.id}", "$('##{s}_button_#{engine.games[engine.current_game].side_for_spells}').removeAttr('disabled');")
          else
            PrivatePub.publish_to("/games/#{@game.id}", "$('##{s}_button_#{engine.games[engine.current_game].side_for_spells}').attr('disabled','disabled');")
          end
        end
      end
    end
    PrivatePub.publish_to("/games/#{@game.id}", "$.ajax({type: 'GET',url: '/games/' + #{@game.id} + '.json',failure: function(msg) {alert('Request unsuccessful, check your internet connection.')},dataType: 'json',success: update});")
  end
  
  def enginemovepromote
    @game = Game.find_by_id(params[:id])
    engine = ObjectCache.find(@game.id.to_s)
    engine.handle_line("move_special 9 #{params[:fromx]} #{params[:fromy]} #{params[:piece]}")
    render text: engine.games[engine.current_game].last_move_okay
    # Enabled publishing (refreshing board) after casting the spell. Previously not present.
    PrivatePub.publish_to("/games/#{@game.id}", "$.ajax({type: 'GET',url: '/games/' + #{@game.id} + '.json',failure: function(msg) {alert('Request unsuccessful, check your internet connection.')},dataType: 'json',success: update});")  
  end
  
  def enginemoveshapeshift
    @game = Game.find_by_id(params[:id])
    engine = ObjectCache.find(@game.id.to_s)
    engine.handle_line("move_special 6")
    render text: engine.games[engine.current_game].last_move_okay
    # Enabled publishing (refreshing board) after casting the spell. Previously not present.
    PrivatePub.publish_to("/games/#{@game.id}", "$.ajax({type: 'GET',url: '/games/' + #{@game.id} + '.json',failure: function(msg) {alert('Request unsuccessful, check your internet connection.')},dataType: 'json',success: update});")  
  end
  
  def enginemovepossession
    @game = Game.find_by_id(params[:id])
    engine = ObjectCache.find(@game.id.to_s)
    engine.handle_line("move_special 5")
    render text: engine.games[engine.current_game].last_move_okay
    # Enabled publishing (refreshing board) after casting the spell. Previously not present.
    PrivatePub.publish_to("/games/#{@game.id}", "$.ajax({type: 'GET',url: '/games/' + #{@game.id} + '.json',failure: function(msg) {alert('Request unsuccessful, check your internet connection.')},dataType: 'json',success: update});")  
  end
  
  def enginemoveflight
    @game = Game.find_by_id(params[:id])
    engine = ObjectCache.find(@game.id.to_s)
    engine.handle_line("move_special 7")
    render text: engine.games[engine.current_game].last_move_okay
    # Enabled publishing (refreshing board) after casting the spell. Previously not present.
    PrivatePub.publish_to("/games/#{@game.id}", "$.ajax({type: 'GET',url: '/games/' + #{@game.id} + '.json',failure: function(msg) {alert('Request unsuccessful, check your internet connection.')},dataType: 'json',success: update});")  
  end
  
  def enginemoveresurrect
    @game = Game.find_by_id(params[:id])
    engine = ObjectCache.find(@game.id.to_s)
    engine.handle_line("move_special 10 #{params[:piece]}")
    render text: engine.games[engine.current_game].last_move_okay
    # Enabled publishing (refreshing board) after casting the spell. Previously not present.
    PrivatePub.publish_to("/games/#{@game.id}", "$.ajax({type: 'GET',url: '/games/' + #{@game.id} + '.json',failure: function(msg) {alert('Request unsuccessful, check your internet connection.')},dataType: 'json',success: update});") 
  end
  
  def enginemovefreeze
    @game = Game.find_by_id(params[:id])
    engine = ObjectCache.find(@game.id.to_s)
    engine.handle_line("move_special 3 #{params[:x]} #{params[:y]}")
    render text: engine.games[engine.current_game].last_move_okay
    # Enabled publishing (refreshing board) after casting the spell. Previously not present.
    PrivatePub.publish_to("/games/#{@game.id}", "$.ajax({type: 'GET',url: '/games/' + #{@game.id} + '.json',failure: function(msg) {alert('Request unsuccessful, check your internet connection.')},dataType: 'json',success: update});")
  end
  
  def enginemovezap    
    @game = Game.find_by_id(params[:id])
    engine = ObjectCache.find(@game.id.to_s)

app/helpers/game_helper.rb
module GameHelper
  def side_finder(arg1,arg2)
    @player_playing_game= PlayerPlayingGame.where(game_id: arg1.to_s, player_side: arg2.to_s).first
    end
end

app/views/games/_blackspells.html.erb
<script>



</script>


<table class="spells" id="black" cellpadding="0" cellspacing="0">
    <tr>
        <td id="blackcauldron" class="spell"><div><%=image_tag("spells/cauldron.png", :alt => "Cauldron", :size => "30x30")%></div>The Cauldron</td>
        <td id="blackspellhammer" class="spell"><div><%=image_tag("spells/spellhammer.png", :alt => "SpellHammer", :size => "30x30")%></div>Spellhammer</td>
        <td id="blackclub" class="spell"><div><%=image_tag("spells/club.png", :alt => "Club", :size => "30x30")%></div>Dagda's Club</td>
        <td id="blackharp" class="spell"><div><%=image_tag("spells/harp.png", :alt => "Harp", :size => "30x30")%></div>Dagda's Harp</td>
        <td id="blackmist" class="spell"><div><%=image_tag("spells/mist.png", :alt => "Mist", :size => "30x30")%></div>Mist</td>
        <td id="blackshield" class="spell"><div><%=image_tag("spells/shield.png", :alt => "Shield", :size => "30x30")%></div>Shield</td>
        <td id="blackshapeshift" class="spell"><div><%=image_tag("spells/shapeshift.png", :alt => "ShapeShift", :size => "30x30")%></div>Shape Shift</td>
        <td id="blackpossession" class="spell"><div><%=image_tag("spells/possession.png", :alt => "Possession", :size => "30x30")%></div>Possession</td>
        <td id="blackflight" class="spell"><div><%=image_tag("spells/flight.png", :alt => "Flight", :size => "30x30")%></div>Flight</td>
    </tr>
</table>

app/views/games/_greenspells.html.erb
<table class="spells" id="green" cellpadding="0" cellspacing="0">
         <tr>
            <td id="greencauldron"><div><%=image_tag("spells/cauldron.png", :alt => "Cauldron", :size => "30x30")%></div>The Cauldron</td>
            <td id="greenspellhammer"><div><%=image_tag("spells/spellhammer.png", :alt => "SpellHammer", :size => "30x30")%></div>Spellhammer</td>
            <td id="greenclub"><div><%=image_tag("spells/club.png", :alt => "Club", :size => "30x30")%></div>Dagda's Club</td>
            <td id="greenharp"><div><%=image_tag("spells/harp.png", :alt => "Harp", :size => "30x30")%></div>Dagda's Harp</td>
            <td id="greenmist"><div><%=image_tag("spells/mist.png", :alt => "Mist", :size => "30x30")%></div>Mist</td>
            <td id="greenshield"><div><%=image_tag("spells/shield.png", :alt => "Shield", :size => "30x30")%></div>Shield</td>
            <td id="greenshapeshift"><div><%=image_tag("spells/shapeshift.png", :alt => "ShapeShift", :size => "30x30")%></div>Shape Shift</td>
            <td id="greenpossession"><div><%=image_tag("spells/possession.png", :alt => "Possession", :size => "30x30")%></div>Possession</td>
            <td id="greenflight"><div><%=image_tag("spells/flight.png", :alt => "Flight", :size => "30x30")%></div>Flight</td>
        </tr>
</table>

app/views/games/_playright.html.erb
          <br/><br/><br/><br/>
          <table id="chess_board1" cellpadding="0" cellspacing="0" width="163">
                  <tr>
                    <td class="mark"><h1>Game information</h1></td>
                  </tr>
                  <tr style="height:200px;">
                    <td id="game_info" class="mark"><h2></h2></td>
                  </tr>
          </table>
          <br/>
          <table id="chess_board1" cellpadding="0" cellspacing="0" width="163">
                  <tr>
                    <td class="mark"><h1>Messaging</h1></td>
                  </tr>
          </table>
                  <%= render "messages/index" %>
          

app/views/games/index.html.erb
<style type="text/css">
  .header a {
      color:#ffffff;
      /*font-size:10px;*/
      text-decoration: none;
      opacity: 0.7;
      /*transition:opacity 0.2s;*/
      &:hover {
      opacity: 1;
      color: #fff;
      text-decoration: none;
      }
  }

  .content {
    display: block;
    position: relative;
    float: left;
  }

  body {
    font-family: 'Open Sans', sans-serif !important;
    font-weight: 400;
    text-rendering: optimizelegibility;
    background-color: #EDF5EB; 
  }

  ul {
    list-style: none;
    -webkit-padding-start: 0;
    -moz-padding-start: 0;
    padding-start: 0;
  }
  .btn {
    opacity: 1;
  }
</style>
<div class="container">
<h1>List of current games <span class="small text-muted">by <% if @owner %><%= @owner.username %><% else %>everyone<% end %></span></h1>
<div class="panel panel-default">
  <div class="panel-heading"><strong>2 player games</strong></div>
  <% if @games2.size == 0 %>
    <div class="panel-body">
      No on going games found.
    </div>
  <% else %>
    <table class="table table-bordered">
      <tr>
        <th>Owner</th>
        <th>Red</th>
        <th>White</th>
        <th></th>
      </tr>
    <% @games2.each do |game| %>
      <tr>
        <td><%= game.owner %></td>
        <td><%= game.red %></td>
        <td><%= game.green %></td>
        <td><%= link_to 'Enter', game %></td>
      </tr>
    <% end %>
    </table>
  <% end %>
</div>
<div class="panel panel-default">
  <div class="panel-heading"><strong>3 player games</strong></div>
  <% if @games3.size == 0 %>
    <div class="panel-body">
      No on going games found.
    </div>
  <% else %>
    <table class="table table-bordered">
      <tr>
        <th>Owner</th>
        <th>Red</th>
        <th>White</th>
        <th>Green</th>
        <th></th>
      </tr>

    <% @games3.each do |game| %>
      <tr>
        <td><%= game.owner %></td>
        <td><%= game.red %></td>
        <td><%= game.white %></td>
        <td><%= game.green %></td>
        <td><%= link_to 'Enter', game %></td>
      </tr>
    <% end %>
    </table>
  <% end %>
</div>
<div class="panel panel-default">
  <div class="panel-heading"><strong>4 player games</strong></div>
  <% if @games.size == 0 %>
    <div class="panel-body">
      No on going games found.
    </div>
  <% else %>
    <table class="table table-bordered">
      <tr>
        <th>Owner</th>
        <th>Red</th>
        <th>White</th>
        <th>Green</th>
        <th>Black</th>
        <th></th>
      </tr>

    <% @games.each do |game| %>
      <tr>
        <td><%= game.owner %></td>
        <td><%= game.red %></td>
        <td><%= game.white %></td>
        <td><%= game.green %></td>
        <td><%= game.black %></td>
        <td><%= link_to 'Enter', game %></td>
      </tr>
     <% end %> 

    </table>
  <% end %>
</div>
<% if @owner %>
  <%= link_to @owner.game_room, :class => "btn btn-default" do %>
      <span class='glyphicon glyphicon-arrow-left'></span> Back to games room
  <% end %>
<% else %>
  <%= link_to playerintro_path, :class => "btn btn-default" do %>
      <span class='glyphicon glyphicon-arrow-left'></span> Back to lobby
  <% end %>
<% end %>
</div>

app/views/games/landing.html.erb
<link href='http://fonts.googleapis.com/css?family=IM+Fell+English+SC' rel='stylesheet' type='text/css'>
<link href="http://netdna.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
<link href='http://fonts.googleapis.com/css?family=IM+Fell+DW+Pica|Alike+Angular' rel='stylesheet' type='text/css'>
<style type="text/css">
  body {
    background-color: #fff;
  }

  .jumbotron {
    /*height: 550px;*/
    background: url(<%= asset_path 'bg1.png' %>) no-repeat center center;
    background-size: 100%;
    margin-bottom: 0;
  }
  .jumbotron h1 {
    font-family: 'IM Fell English SC', serif;
    font-size: 5em;
    padding-top: 50px;
    color: #fff;
    text-align: center;
    letter-spacing: 50px;
  }

  .jumbotron p {
    font-family: 'IM Fell DW Pica', serif;
    -webkit-animation-delay: 1s;
    -moz-animation-delay: 1s;
    color: #fff;
    font-size: 24px;
    text-align: center;
  }

  .btn-success {
    font-family: 'Alike Angular', serif; 
    background-color: #759B69;
    border: 1px solid #265218;
    color: #fff;
  }

  .btn-success:hover, .btn-success:focus {
    background-color: #567E4A;
    border: 1px solid #265218;
  }

  .btn-success:active {
    background-color: #567E4A;
    border: 1px solid #265218;
  }

  #lore {
    background-color: #EDF5EB;
  }

  .footer {
    background-color: transparent;
    color: gray;
  }

  .footer .container {
    padding-bottom: 20px;
  }

  h2 { 
    font-family: 'Alike Angular', serif;
    font-size: 40px;
    font-weight: 300;
    letter-spacing: -1px;
    line-height: 50px;
  }
  @media screen and (max-width: 570px) {
    .jumbotron {
      background-size: auto 100%;
    }
    .jumbotron h1 {
      font-size: 3em;
      letter-spacing: 20px;
    }
  }
</style>
<div id="title" class="jumbotron">
  <h1 align="center">CELTIA</h1><br/>
  <p align="center">The game of the Gods</p><br/><br/><br/>
  <p align="center"><%= link_to "Play online now!", playerintro_path, :class => "btn btn-success btn-lg" %></p>
</div>
<div class="lore" id="lore">
  <br/>
  <div class="container">
      <h2>Lore</h2><br/>
        <div class="row">
            <div class="col-md-3 col-md-push-9 text-center">
                <img class="img-circle" src="<%= asset_path 'cauldron.png' %>" height="150" />
            </div>
            <div class="col-md-9 col-md-pull-3">
                <p>
                  For long ages the history and folk lore of the clans and their cultural traditions have been kept by the Seannaiches. For they alone have been the guardians of the secrets of the true, Inner Celtia. To them the lands held treasures among the old tales and divine magic that is in each and every one of us. Now as the new millennium enfolds in front of us mankind will be ill-fitted to embrace their awaiting destiny without the lost treasures of the human soul. The cauldron of Dragda, held by Morigu in the land of shadows, is without a doubt among the greatest of the treasures but no champion has arisen who could lay claim to it. No longer can such a quest be reserved for warriors, as time is running out any brave soul can try to take back the cauldron from Morigu.
                  <p><strong>Good Luck</strong></p> Read the Full <%= link_to "Story here!", story_path %>
                </p>
            </div>
        </div>
      
  </div>
  <br/><br/>
</div>
    <div class="buy" id="buy">
    <br/>
      <div class="container">
        <div class="row">
          <div class="col-md-4 col-sm-4">
            <h2>Buy now</h2>
            <p>
              Available from: <br/><a href="http://www.amazon.co.uk/Celtia-The-Original-Game-Gods/dp/B00HJ7WFM8/ref=sr_1_1?ie=UTF8&qid=1402481495&sr=8-1&keywords=celtia+board+game">Amazon UK</a><br/>
              <a href="http://www.celtia.co/html/setsandxtras.html">Celtia Official site</a>
            </p>
          </div>  
          <div class="col-md-4 col-sm-4">
            <h2>Contact</h2>
            <p>
              Shadowland games LLP<br/>
              Ardarroch Court<br/>
              Laroch Beag<br/>
              Ballachulish<br/>
              Scotland<br/>
              PH49 4LG<br/>
              <a href="mailto:sales@celtia.co?Subject=Hello" target="_top">sales@celtia.co</a><br/>
              0776672 85533
            </p>
          </div>
          <div class="col-md-4 col-sm-4">
            <h2>Credits</h2>
            <p>Graham McKay<br/>
            Bruce Scharlau<br/>
            Megan Inch<br/>
            Chris Wilson<br/>
            Orinemia Ajulo<br/>
            Colloque Tsui</p>
          </div>
        </div>
      </div>
    </div>
  <!-- Login popup -->
  <div class="modal fade" id="login-form" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
          <h4 class="modal-title" id="myModalLabel">Login</h4>
        </div>
        <%= form_tag sessions_path do %>
        <div class="modal-body">
          <div class="form-group">
              <label for="email">Email</label>
              <%= text_field_tag :email, params[:email], :class => "form-control", :placeholder => 'Email', :type => "email" %>
          </div>
          <div class="form-group">
              <label for="password">Password</label>
              <%= password_field_tag :password, nil, :class => "form-control", :placeholder => 'Password' %>
          </div>
              <%= check_box_tag :remember_me, 1, params[:remember_me], {checked: true} %>
              <%= label_tag :remember_me, 'Stay signed in' %>
              <span class="pull-right"><%= link_to "Forgot?", new_password_reset_path %></span>
          </div>
          <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
              <%= submit_tag "Log In", :class => "btn btn-success" %>
              <a class="pull-left" href="#" data-toggle="modal" data-target="#register-form" data-dismiss="modal">New user? Register now!</a>
          </div> 
        <% end %>
      </div>
    </div>
  </div>
  <!-- Register popup -->
  <div class="modal fade" id="register-form" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
          <h4 class="modal-title" id="myModalLabel">Register</h4>
        </div>
        <%= form_for @player do |f| %>
        <div class="modal-body">
          <div class="form-group">
            <%= f.label :'username' %>
            <%= f.text_field :username, :class => "form-control", :placeholder => 'Username' %>
          </div>
          <div class="form-group">
            <%= f.label :'email' %>
            <%= f.text_field :email, :class => "form-control", :placeholder => 'Email', :type => "email" %>
          </div>
          <div class="form-group">
            <%= f.label :'password' %>
            <%= f.password_field :password, :class => "form-control", :placeholder => 'Password' %>
          </div>
          <div class="form-group">
            <%= f.label :'password_confirmation' %>
            <%= f.password_field :password_confirmation, :class => "form-control", :placeholder => 'Password confirmation' %>
          </div>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <%= submit_tag "Register", :class => "btn btn-success" %>
            <a class="pull-left" href="#" data-toggle="modal" data-target="#login-form" data-dismiss="modal">Already registered?</a>
        </div> 
        <% end %>
      </div>
    </div>
  </div>

app/views/games/show.js.erb
<% publish_to "/games/#{@game.id}" do %>
  alert('asd');
<% end %>