config/routes.rb
Celtia::Application.routes.draw do


  get "password_resets/new"

  resources :players
  resources :sessions
  resources :password_resets
  resources :game_rooms
  resources :messages do
  
  member do
  
  get "message_list" 
  end
  
  
  end

  resources :games do
   
  #get 'update_game_red', :on => :member, :as => update_game_red

    member do
      get "last_moved"
      get "turn_counter"
      put 'update_game_red'
      post "command"
      post "enginemove2"
      post "enginemovepromote"
      post "enginemovewildcard"
      post "enginemoveresurrect"
      post "enginemoveshapeshift"
      post "enginemovepossession"
      post "enginemoveflight"
      post "enginemovefreeze"
      post "enginemovezap"
      post "enginemoveshield"
      post "enginemovemist"
      post "random_move"
      post "use_ai"
      put "play_as_white"
      put "play_as_red"
      put "play_as_green"
      put "play_as_black"
    end

    #resource :whites, only: [:show]
    #resource :blacks, only: [:show]
    #resource :greens, only: [:show]
    #resource :reds, only: [:show]
  end

  get "/usage", :to => "games#usage", :as => :usage
  get "/story", :to => "home#storyboard", :as => "story"
  get "/lobby", :to => "lobby#show", :as => "playerintro"

  resource :error, only: [:show]

  root to: "games#landing"
end

app/models/player.rb
class Player < ActiveRecord::Base
has_many :player_lists
has_many :messages
has_many :games, through: :player_playing_games
has_one :game_room


  attr_accessible :email, :password, :password_confirmation, :username
  has_secure_password
  
  validates_uniqueness_of :email, :username
  validates :username, :presence => true
  validates :email, :presence => true
  validates_length_of :password, minimum: 6, on: :create
  before_create { generate_token(:auth_token) }
  
  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while Player.exists?(column => self[column])
  end

  def send_password_reset
	  generate_token(:password_reset_token)
	  self.password_reset_sent_at = Time.zone.now
	  save!
	  PlayerMailer.password_reset(self).deliver
	end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  respond_to :html, :js
  before_filter :authorize, only: [:show, :edit, :update]
  # before_filter :update_last_seen


  def show
    @player = Player.find(params[:id])
  end
  
  def new
    @player = Player.new
  end
  
  def create
    @player = Player.new(params[:player])
    if @player.save
     cookies[:auth_token] = @player.auth_token 
      redirect_to root_url, notice: "Thank you for registering."
    else
      render "new"
    end
  end

  def edit
      @player = Player.find(params[:id])
  end

  def update
    @player = Player.find(params[:id])
    Game.where("owner = ?", @player.username).update_all :owner => player_params[:username]
    if @player.update_attributes(player_params)
       #Game.where('owner ?', params[:owner == @player.username]).update_all(player_params[:username])
       redirect_to @player, notice: "Profile updated"
    else
      render 'edit'
    end
  end

  private 
    def player_params
      params.require(:player).permit(:username, :email, :password, :password_confirmation)
    end
end

app/views/players/edit.html.erb
<div class="container">
	<ol class="breadcrumb">
	  <li><a href="/">Home</a></li>
	  <li><%= link_to "#{@player.username}'s Profile", @player %></li>
	  <li class="active">Edit details</li>
	</ol>
	<div class="col-md-6 col-md-offset-3">
		<div class="panel panel-default">
		<div class="panel-heading">Update your profile</div>
		<div class="panel-body">
			<%= form_for(@player) do |f| %>
			<% if @player.errors.any? %>
			    <div class="alert alert-error">
			      <strong>A few errors...</strong>
			      <ul>
			        <% @player.errors.full_messages.each do |message| %>
			          <li><%= message %></li>
			        <% end %>
			      </ul>
			    </div>
			    <br/>
			<% end %>
			<div class="form-group">
				<%= f.label :'username', :class => "control-label" %>
				<%= f.text_field :username, :placeholder => "Username", :class => "form-control" %>
			</div>
			<div class="form-group">
				<%= f.label :'email', :class => "control-label" %>
				<%= f.text_field :email, :placeholder => "Email", :type => "email", :class => "form-control" %>
			</div>
			<div class="form-group">
				<%= f.label :'password', :class => "control-label" %>
				<%= f.password_field :password, :placeholder => "Password", :class => "form-control" %>
			</div>
			<div class="form-group">
				<%= f.label :'password_confirmation', :class => "control-label" %>
				<%= f.password_field :password_confirmation, :placeholder => "Confirm Password", :class => "form-control" %>
			</div>
			<p align="right">
				<%= link_to "Cancel", @player, :class => "btn btn-default" %>
				<%= f.submit "Save changes", class: "btn btn-success" %>
			</p>
			<% end %>
		</div>
	</div>
	</div>
</div>

app/views/players/new.html(original).erb
<h1>Sign Up</h1>

<%= form_for @player do |f| %>
  <% if @player.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @player.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

    <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit "Sign Up" %></div>
<% end %>

app/views/players/new.html.erb
<div class="container">
<ol class="breadcrumb">
  <li><a href="/">Home</a></li>
  <li class="active">Register</li>
</ol>
<div class="col-md-6 col-md-offset-3">

<div class="panel panel-default">
<div class="panel-heading">Register for Celtia!</div>
<div class="panel-body">
<%= form_for @player do |f| %>
         <% if @player.errors.any? %>
         <div class="alert alert-alert">
            <strong>Form is invalid</strong>
            <ul>
                <% @player.errors.full_messages.each do |message| %>
                <li><%= message %></li>
                <% end %>
            </ul>
        </div>
        <br/>
        <% end %>
        <div class = "form-group">
        	<%= f.label :email %>
			<%= f.text_field :email, :placeholder => "Enter your email", :class => "form-control" %>
        </div>
        <div class = "form-group">
        	<%= f.label :username %>
			<%= f.text_field :username, :placeholder => "Enter your username", :class => "form-control" %>
        </div>
        <div class = "form-group">
			<%= f.label :password %>
			<%= f.password_field :password, :placeholder => "Enter your password", :class => "form-control" %>
        </div>
        <div class = "form-group">
			<%= f.label :password_confirmation %>
			<%= f.password_field :password_confirmation, :placeholder => "Enter your password again", :class => "form-control" %>
        </div>
        <p align="right">
        <%= submit_tag("Reset", { :name => 'reset', :class => 'btn btn-default', :type => "reset" }) %>
        <%= f.submit 'Register', :class => "btn btn-success" %>
        </p>
<% end %>
</div>
</div>
</div>
</div>

app/views/players/show.html.erb
<div class="container">
	<ol class="breadcrumb">
	  <li><a href="/">Home</a></li>
	  <li class="active"><%= @player.username %>'s Profile</li>
	</ol>
	<div class="col-md-6 col-md-offset-3">
		<div class="panel panel-default">
		<div class="panel-heading"><span class="glyphicon glyphicon-user"></span> <%= @player.username %>'s Profile</div>
		<table class="table table-bordered">
			<% if @player.username == current_player.username %>
			<tr>
				<td><span class="glyphicon glyphicon-envelope"></span> Email:</td>
				<td><%= @player.email %></td>
			</tr>
			<% end %>
			<tr>
				<td><span class="glyphicon glyphicon-star"></span> Rating:</td>
				<td><%= @player.rating %></td>
			</tr>
			<tr>
				<td><span class="glyphicon glyphicon-stats"></span> Skill level:</td>
				<td><%= player_level %></td>
			</tr>
			<tr>
				<td colspan="2">
					<%= link_to playerintro_path, :class => "btn btn-default" do %>
						<span class='glyphicon glyphicon-arrow-left'></span> Back to lobby
					<% end %>
					<%= link_to games_path(owner: @player.username), method: :get, :class => "btn btn-primary" do %>
					   <span class="glyphicon glyphicon-eye-open"></span> View games by <%= @player.username %>
					<% end %>
					<% if @player.username == current_player.username %>
						<%= link_to edit_player_path(current_player), :class => "btn btn-success pull-right" do %>
							<span class="glyphicon glyphicon-cog"></span> Settings
						<% end %>
					<% end %>
				</td>
			</tr>
		</table>
		</div>
	</div>
</div>